language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  
addons:
  chrome: stable
  firefox: latest
    
    

- wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d 
/home/travis/virtualenv/python3.6/bin/
- export CHROME_BIN=chromium-browser



before_script:
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
