language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

- wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d 
/home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser

before_script:
